routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// Route::get('/migrate', 'LinkController@cache');
// Route::get('/key', 'LinkController@artisankey');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('auth/{provider}', 'Auth\SocialAuthController@redirectToProvider')->name('social.auth');
Route::get('auth/{provider}/callback', 'Auth\SocialAuthController@handleProviderCallback');
Route::post('/home', 'HomeController@mercadopago')->name('mercadopago');
Route::get('/terminos', 'LinkController@terminos')->name('terminos');


Route::middleware(['auth'])->name('backoffice.')->group(function() {

    Route::prefix('/account')->name('account.')->group(function() {
        Route::get('/', 'AccountController@index')->name('index');
        Route::get('/create', 'AccountController@create')->name('create');
        Route::post('/store', 'AccountController@store')->name('store');
        Route::get('/{id}', 'AccountController@show')->name('show');
        Route::prefix('/{account_id}/hashtags')->name('hashtags.')->group(function() {
            Route::post('/store', 'HashtagsController@store')->name('store');
        });
    });

    Route::prefix('/profile')->name('profile.')->group(function() {
        Route::get('/', 'ProfileController@index')->name('index');
    });

    Route::prefix('setttings')->name('settings.')->group(function() {
        Route::get('/', 'LinkController@configurar')->name('index');
    });

    Route::middleware(['admin'])->prefix('/admin')->name('admin.')->group(function () {

        Route::prefix('/clients')->name('clients.')->group(function() {
            Route::get('/', 'ClientsController@index')->name('index');
            Route::get('/{id}', 'ClientsController@show')->name('show');
        });

        Route::prefix('/droplets')->name('droplets.')->group(function() {
            Route::get('/', 'DropletsController@index')->name('index');
            Route::post('/store', 'LinkController@store')->name('store');
            Route::delete('/destroy', 'DropletsController@destroy')->name('destroy');
        });

    });


    Route::get('/configurar', 'LinkController@configurar')->name('configurar');
    Route::post('/configurar', 'HomeController@update')->name('update');
    Route::get('{id}/baja', 'HomeController@baja')->name('baja');
    Route::get('/pagoconfirmado', 'LinkController@pagoconfirmado')->name('pagoconfirmado');
});


//RUTAS BACKOFFICE
Route::group(['middleware' => ['auth', 'admin']], function () {
    Route::get('/gestion', 'LinkController@backoffice')->name('backoffice');
    Route::get('/gestion/{id}', 'LinkController@showUser')->name('showUser');
    Route::get('/migrate', 'LinkController@migrate');
});

app/Account.php
<?php

namespace App;

use App\hashtags;
use Illuminate\Database\Eloquent\Model;

class Account extends Model
{
    public function hashtags()
    {
        return $this->hasMany(Hashtag::class);
    }
}

app/Http/Controllers/AccountController.php
<?php

namespace App\Http\Controllers;

use App\Account;
use Illuminate\Http\Request;
use App\Http\Services\DropletService;

class AccountController extends Controller
{

    /**
     * DropletService
     * @var \App\Http\Services\DropletService
     */
    private $dropletService;

    /**
     * Constructor 
     * @param \App\Http\Services\DropletService $dropletService
     */
    public function __construct(DropletService $dropletService)
    {
        $this->dropletService = $dropletService;
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $accounts = Account::where('user_id', $request->user()->id)->get();
        return view('backoffice.account.index')->with('accounts', $accounts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backoffice.account.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'username' => 'required',
            'password' => 'required',
        ]);

        try {
            return redirect($this->dropletService->processAccount($request));
        } catch (Exeption $ex) {
            dd($ex->message);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        $account = Account::where('user_id', $request->user()->id)->where('id', $id)->first();
        if ($account) {
            return view('backoffice.account.show')->with('account', $account);
        }
        return abort(404);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backoffice/account/create.blade.php
@extends('layouts.app')

@section('content')


<div class="row">
    <div class="col-lg-9 mx-auto">
        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Add new account</h1>
        </div>
        
        <!-- Basic Card Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Instagram login</h6>
            </div>
            <div class="card-body">
                <form action="{{ route('backoffice.account.store') }}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="exampleInputEmail1">Email address</label>
                        <input type="email" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                    </div>
                    <div class="form-group form-check">
                        <input type="checkbox" class="form-check-input" id="exampleCheck1">
                        <label class="form-check-label" for="exampleCheck1">Check me out</label>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
        
    </div>
    
</div>


@endsection

resources/views/backoffice/account/index.blade.php
@extends('layouts.app')

@section('content')
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800"><i class="fab fa-instagram mx-2"></i> Accounts</h1>
    <a href="{{ route('backoffice.account.create') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-plus fa-sm text-white-50"></i> Add account</a>
</div>
<div class="row">
    @foreach ($accounts as $account)
    <div class="col-lg-4">
        <!-- Dropdown Card Example -->
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">{{$account->username}}</h6>
                <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                        <div class="dropdown-header">Dropdown Header:</div>
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </div>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                Status: <br>
                <a href="{{route('backoffice.account.show', $account->id)}}" class="btn btn-primary">Config</a>
            </div>
        </div>
    </div>
    @endforeach
</div>

@endsection

resources/views/backoffice/account/show.blade.php
@extends('layouts.app')

@section('content')

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Account - {{ $account->username }}</h1>
</div>

<div class="row">
    <div class="col-lg-4">
        <!-- Basic Card Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Hastags # de Referencia</h6>
            </div>
            <div class="card-body">
                <form action="{{ route('backoffice.account.hashtags.store', $account->id) }}" method="POST">
                    @csrf
                    @php $hashtag_count = 1; @endphp
                    @foreach ($account->hashtags as $key => $hashtag)
                    <div class="form-group">
                        <label for="hashtag-{{ $hashtag_count }}">Hashtag {{ $hashtag_count }}</label>
                        <input type="text" name="hashtags[]" id="hashtag-{{$hashtag_count}}" class="form-control" value="{{$hashtag->value}}">
                    </div>
                    @php $hashtag_count++; @endphp
                    @endforeach
                    <div class="form-group">
                        <label for="hashtag-{{ $hashtag_count }}">Hashtag {{ $hashtag_count }}</label>
                        <input type="text" name="hashtags[]" id="hashtag-{{$hashtag_count}}" class="form-control">
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <!-- Basic Card Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Cuentas de Referencia</h6>
            </div>
            <div class="card-body">
                <p>Los nombres de usuario de tus competidores. Usamos sus cuentas para interactuar con sus seguidores, la gente que les comenta y hace likes.</p>
                <form action="{{ route('backoffice.account.store') }}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="exampleInputEmail1">Referencia 1:</label>
                        <input type="email" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <!-- Basic Card Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Funcionalidades</h6>
            </div>
            <div class="card-body">
                <p>Seleccione las funcionalidades que quieres que usemos en tu cuenta.</p>
                <form action="{{ route('backoffice.account.store') }}" method="POST">
                    @csrf
                    <div class="row">
                        <div class="col-sm-6 form-group">
                            <label for="exampleInputEmail1">Seguir y dejar de Seguir:</label>
                            <input type="email" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                        </div>
                        <div class="col-sm-6 form-group">
                            <label for="exampleInputEmail1">Ignorar Usuarios Privados:</label>
                            <input type="email" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                        </div>
                        <div class="col-sm-6 form-group">
                            <label for="exampleInputEmail1">Likes:</label>
                            <input type="email" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                        </div>
                        <div class="col-sm-6 form-group">
                            <label for="exampleInputEmail1">Comentarios:</label>
                            <input type="email" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
    
</div>

@endsection