routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// Route::get('/migrate', 'LinkController@cache');
// Route::get('/key', 'LinkController@artisankey');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('auth/{provider}', 'Auth\SocialAuthController@redirectToProvider')->name('social.auth');
Route::get('auth/{provider}/callback', 'Auth\SocialAuthController@handleProviderCallback');
Route::post('/home', 'HomeController@mercadopago')->name('mercadopago');
Route::get('/terminos', 'LinkController@terminos')->name('terminos');


Route::middleware(['auth'])->name('backoffice.')->group(function() {

    Route::prefix('/account')->name('account.')->group(function() {
        Route::get('/', 'AccountController@index')->name('index');
        Route::get('/create', 'AccountController@create')->name('create');
        Route::post('/store', 'AccountController@store')->name('store');
        Route::get('/{id}', 'AccountController@show')->name('show');
        Route::prefix('/{account_id}/hashtags')->name('hashtags.')->group(function() {
            Route::post('/store', 'HashtagsController@store')->name('store');
        });
    });

    Route::prefix('/profile')->name('profile.')->group(function() {
        Route::get('/', 'ProfileController@index')->name('index');
    });

    Route::prefix('setttings')->name('settings.')->group(function() {
        Route::get('/', 'LinkController@configurar')->name('index');
    });

    Route::middleware(['admin'])->prefix('/admin')->name('admin.')->group(function () {

        Route::prefix('/clients')->name('clients.')->group(function() {
            Route::get('/', 'ClientsController@index')->name('index');
            Route::get('/{id}', 'ClientsController@show')->name('show');
        });

        Route::prefix('/droplets')->name('droplets.')->group(function() {
            Route::get('/', 'DropletsController@index')->name('index');
            Route::post('/store', 'LinkController@store')->name('store');
            Route::delete('/destroy', 'DropletsController@destroy')->name('destroy');
        });

    });


    Route::get('/configurar', 'LinkController@configurar')->name('configurar');
    Route::post('/configurar', 'HomeController@update')->name('update');
    Route::get('{id}/baja', 'HomeController@baja')->name('baja');
    Route::get('/pagoconfirmado', 'LinkController@pagoconfirmado')->name('pagoconfirmado');
});


//RUTAS BACKOFFICE
Route::group(['middleware' => ['auth', 'admin']], function () {
    Route::get('/gestion', 'LinkController@backoffice')->name('backoffice');
    Route::get('/gestion/{id}', 'LinkController@showUser')->name('showUser');
    Route::get('/migrate', 'LinkController@migrate');
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta name="google-site-verification" content="BGmK5vCFVQ9Lxu-oonAG9W1afrIR7iYNHGJPPNV0Cxc" />
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-T8VLC9M');</script>
    <!-- End Google Tag Manager -->
    
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Juanziz Spada">
    <link rel="icon" type="png" href="/img/favicon.png">
    
    <title>Más Follows</title>
    
    <!-- Custom fonts for this template -->
    <link href="/backoffice/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    
    <!-- Custom styles for this template -->
    <link href="/backoffice/css/sb-admin-2.css" rel="stylesheet">
    
    <!-- Custom styles for this page -->
    <link href="/backoffice/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
    
    
</head>

<body id="page-top">
    
    <!-- Page Wrapper -->
    <div id="wrapper">
        
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            
            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ (auth()->guard()->check()) ?  route('backoffice.account.index') : '/' }}">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Más <sup>Follows</sup></div>
            </a>

            @auth
            <!-- Divider -->
            <hr class="sidebar-divider my-0">
            
            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="{{ route('backoffice.account.index') }}">
                    <i class="fab fa-instagram"></i>
                    <span>{{ trans('backoffice.sidebar.accounts') }}</span>
                </a>
            </li>
            
            @if (Auth::user()->role == 0)
            <!-- Divider -->
            <hr class="sidebar-divider">
            <!-- Heading -->
            <div class="sidebar-heading">
                {{ trans('backoffice.sidebar.admin') }}
            </div>
            
            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link" href="{{ route('backoffice.admin.clients.index') }}">
                    <i class="fas fa-users"></i>
                    <span>{{ trans('backoffice.sidebar.clients') }}</span></a>
                </a>
            </li>
            
            <li class="nav-item">
                <a class="nav-link" href="{{ route('backoffice.admin.droplets.index') }}">
                    <i class="fas fa-server"></i>
                    <span>{{ trans('backoffice.sidebar.droplets') }}</span></a>
                </a>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider">
            @endauth
            <hr class="sidebar-divider d-none d-md-block">
            @endif;

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
            
        </ul>
        <!-- End of Sidebar -->
        
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            
            <!-- Main Content -->
            <div id="content">
                
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                    
                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
                    
                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                        
                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>
                        @auth
                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ Auth::user()->name }}</span>
                                <img class="img-profile rounded-circle" src="{{ Auth::user()->avatar }}">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="{{ route('backoffice.profile.index') }}">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Perfil
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#"  onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                        @endauth
                        @guest
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link" href="{{ route('register') }}">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Register</span>
                            </a>
                        </li>
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link" href="{{ route('login') }}">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Login</span>
                            </a>
                        </li>
                        @endguest
                        
                    </ul>
                    
                </nav>
                <!-- End of Topbar -->
                
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    
                    @yield('content')                        
                    
                </div>
                <!-- /.container-fluid -->
                
            </div>
            <!-- End of Main Content -->
            
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; MásFollows {{ now()->year }}</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->
            
        </div>
        <!-- End of Content Wrapper -->
        
    </div>
    <!-- End of Page Wrapper -->
    
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    
    <!-- Bootstrap core JavaScript-->
    <script src="/backoffice/vendor/jquery/jquery.min.js"></script>
    <script src="/backoffice/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    
    <!-- Core plugin JavaScript-->
    <script src="/backoffice/vendor/jquery-easing/jquery.easing.min.js"></script>
    
    <!-- Custom scripts for all pages-->
    <script src="/backoffice/js/sb-admin-2.min.js"></script>
    
    <!-- Page level plugins -->
    <script src="/backoffice/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="/backoffice/vendor/datatables/dataTables.bootstrap4.min.js"></script>
    
    <!-- Page level custom scripts -->
    <script src="/backoffice/js/demo/datatables-demo.js"></script>
    
    <!-- Start of HubSpot Embed Code -->
    <script type="text/javascript" id="hs-script-loader" async defer src="//js.hs-scripts.com/6012790.js"></script>
    <!-- End of HubSpot Embed Code -->
</body>

</html>